<?php
/**
 * Hemp & Barrel — WebP Auto-Conversion
 * Add this entire block to your WordPress functions.php
 *
 * Features:
 *  1. Auto-converts every newly uploaded image to WebP (quality 85)
 *  2. Converts all thumbnail sizes generated by WP
 *  3. Serves WebP via htaccess (no plugin needed)
 *  4. Falls back gracefully if browser doesn't support WebP
 */

/* ─── 1. Convert new uploads & all their sizes to WebP ─── */
add_filter( 'wp_generate_attachment_metadata', 'hb_generate_webp', 10, 2 );

function hb_generate_webp( $metadata, $attachment_id ) {
    if ( ! function_exists( 'imagewebp' ) ) return $metadata; // GD not available

    $mime = get_post_mime_type( $attachment_id );
    if ( ! in_array( $mime, [ 'image/jpeg', 'image/jpg', 'image/png' ], true ) ) {
        return $metadata;
    }

    $file    = get_attached_file( $attachment_id );
    $dir     = trailingslashit( dirname( $file ) );

    // Convert original
    hb_make_webp( $file, $mime );

    // Convert every registered thumbnail size
    if ( ! empty( $metadata['sizes'] ) ) {
        foreach ( $metadata['sizes'] as $size ) {
            hb_make_webp( $dir . $size['file'], 'image/' . pathinfo( $size['file'], PATHINFO_EXTENSION ) );
        }
    }

    return $metadata;
}

function hb_make_webp( string $src, string $mime, int $quality = 85 ): void {
    if ( ! file_exists( $src ) ) return;

    $dest = preg_replace( '/\.(jpe?g|png)$/i', '.webp', $src );
    if ( file_exists( $dest ) ) return; // already converted

    switch ( strtolower( $mime ) ) {
        case 'image/jpeg':
        case 'image/jpg':
            $img = imagecreatefromjpeg( $src );
            break;
        case 'image/png':
            $img = imagecreatefrompng( $src );
            if ( $img ) {
                imagealphablending( $img, false );
                imagesavealpha( $img, true );
            }
            break;
        default:
            return;
    }

    if ( $img ) {
        imagewebp( $img, $dest, $quality );
        imagedestroy( $img );
    }
}

/* ─── 2. Serve WebP via WordPress (no .htaccess edit needed) ─── */
add_filter( 'wp_get_attachment_image_src', 'hb_serve_webp_src', 10, 3 );

function hb_serve_webp_src( $image, $attachment_id, $size ) {
    if ( ! $image ) return $image;

    // Only swap if browser supports WebP
    if ( empty( $_SERVER['HTTP_ACCEPT'] ) ||
         strpos( $_SERVER['HTTP_ACCEPT'], 'image/webp' ) === false ) {
        return $image;
    }

    $upload_dir  = wp_upload_dir();
    $src         = $image[0];
    $relative    = str_replace( $upload_dir['baseurl'], $upload_dir['basedir'], $src );
    $webp_file   = preg_replace( '/\.(jpe?g|png)$/i', '.webp', $relative );
    $webp_url    = preg_replace( '/\.(jpe?g|png)$/i', '.webp', $src );

    if ( file_exists( $webp_file ) ) {
        $image[0] = $webp_url;
    }

    return $image;
}

/* ─── 3. WC Store API nonce for headless cart ─── */
add_action( 'rest_api_init', function () {
    register_rest_route( 'hemp/v1', '/cart-nonce', [
        'methods'             => 'GET',
        'callback'            => function () {
            return new WP_REST_Response( [ 'nonce' => wp_create_nonce( 'wc_store_api' ) ], 200 );
        },
        'permission_callback' => '__return_true',
    ] );
} );

/* ─── 4. One-time bulk convert existing images ─── */
// Visit: yourdomain.com/wp-admin/ → Appearance → Theme File Editor → functions.php
// Then go to: yourdomain.com/?hb_bulk_webp=1 (only works when logged in as admin)
// REMOVE this block after running once.

add_action( 'init', 'hb_bulk_convert_existing' );

function hb_bulk_convert_existing() {
    if (
        ! isset( $_GET['hb_bulk_webp'] ) ||
        $_GET['hb_bulk_webp'] !== '1'    ||
        ! current_user_can( 'manage_options' )
    ) {
        return;
    }

    set_time_limit( 600 ); // allow 10 min for large libraries

    $attachments = get_posts( [
        'post_type'      => 'attachment',
        'post_mime_type' => [ 'image/jpeg', 'image/jpg', 'image/png' ],
        'posts_per_page' => -1,
        'fields'         => 'ids',
    ] );

    $converted = 0;
    $skipped   = 0;

    foreach ( $attachments as $id ) {
        $file = get_attached_file( $id );
        $mime = get_post_mime_type( $id );
        $dir  = trailingslashit( dirname( $file ) );
        $meta = wp_get_attachment_metadata( $id );

        hb_make_webp( $file, $mime );

        if ( ! empty( $meta['sizes'] ) ) {
            foreach ( $meta['sizes'] as $size ) {
                hb_make_webp( $dir . $size['file'], 'image/' . pathinfo( $size['file'], PATHINFO_EXTENSION ) );
            }
        }

        $webp = preg_replace( '/\.(jpe?g|png)$/i', '.webp', $file );
        file_exists( $webp ) ? $converted++ : $skipped++;
    }

    wp_die(
        "<h2>✅ WebP Bulk Conversion Done</h2>
         <p><strong>Converted:</strong> {$converted} images</p>
         <p><strong>Skipped / Failed:</strong> {$skipped}</p>
         <p>Remove the <code>hb_bulk_convert_existing()</code> block from functions.php now.</p>
         <a href='/wp-admin'>← Back to Dashboard</a>"
    );
}
